export const clientConfig = {
  clientId: "mastercard",
  clientName: "Mastercard",
  productName: "Mastercard Content Atlas",
  pilotTopic: "Cybersecurity",
  language: "English",
  marketScope: ["Global", "US", "UK", "Europe", "Asia Pacific", "Regional English"],
  lastSeededAt: "2026-06-18",
};

export const taxonomy = {
  topics: [
    "Cybersecurity",
    "Fraud prevention",
    "Identity",
    "Authentication",
    "Cyber resilience",
    "Trust",
    "Risk",
    "Data protection",
    "Tokenization",
    "Scams",
    "AI security",
    "Small business security",
    "Post-quantum security",
    "Threat intelligence",
  ],
  audiences: [
    "Consumers",
    "Small businesses",
    "Enterprises",
    "Merchants",
    "Banks",
    "Issuers",
    "Acquirers",
    "Fintechs",
    "Public sector",
    "Developers",
    "Policymakers",
    "Sales teams",
    "Marketing teams",
  ],
  businessAreas: [
    "Cyber and intelligence",
    "Payments",
    "Commercial payments",
    "Open banking/open finance",
    "Digital identity",
    "Data and services",
    "Tokenization",
    "Small business",
    "Consumer protection",
  ],
  funnelStages: [
    "Awareness",
    "Education",
    "Proof",
    "Consideration",
    "Sales enablement",
    "Retention",
    "Thought leadership",
  ],
  usefulness: [
    "Campaign hero asset",
    "Supporting proof point",
    "Sales follow-up",
    "Social-selling asset",
    "Executive POV",
    "Report/statistic source",
    "Background reading",
    "Low current utility",
  ],
  metadataStatuses: ["AI suggested", "Human approved", "Human edited", "Rejected"],
};

export const contentAssets = [
  {
    id: "mc-cyber-overview",
    title: "Cybersecurity & Fraud Prevention",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Solution page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "Mastercard describes its cybersecurity and fraud prevention offer as data, AI, technology and expertise for combating fraud and protecting digital ecosystems. The page groups solutions across cybersecurity, identity, financial crime, risk decisioning and payment resiliency.",
    summary:
      "A primary solution hub for Mastercard's cybersecurity and fraud prevention proposition, useful as the landing asset for an integrated campaign.",
    primary_topic: "Cybersecurity",
    secondary_topics: ["Fraud prevention", "Identity", "Risk", "Tokenization", "Scams"],
    audience: ["Enterprises", "Banks", "Merchants", "Fintechs"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Awareness",
    key_claims: [
      "Mastercard positions data, AI and network expertise as core to combating fraud.",
      "The page reports 32 million cybersecurity and identity risk events assessed daily, based on Mastercard 2026 data.",
      "The page reports 4 billion tokenized transactions secured each month, based on Mastercard 2026 data.",
    ],
    proof_points: [
      "$77.4 billion in fraud prevented to date with Mastercard Safety Net, cited as Mastercard 2026 data.",
      "32 million risk events assessed every day with cybersecurity and identity services, cited as Mastercard 2026 data.",
      "4 billion tokenized transactions secured every month, cited as Mastercard 2026 data.",
    ],
    suggested_use:
      "Use as the hero destination for a cybersecurity audit or awareness campaign, then route readers into solution-specific pages.",
    suggested_sales_enablement_use:
      "Anchor discovery conversations with banks, merchants and enterprises that need an overview of Mastercard's risk capabilities.",
    linkedin_copy_recommendations: {
      executive:
        "Security is now a growth requirement, not a back-office concern. Mastercard's cybersecurity and fraud prevention portfolio shows how data, AI and ecosystem intelligence can help protect digital commerce at scale. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention.html",
      sales:
        "If your teams are managing fraud, identity and cyber risk separately, this Mastercard hub is a useful starting point. It brings together the core solutions for securing digital interactions and reducing risk exposure. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention.html",
      launch:
        "New campaign angle: securing commerce for all. Start with Mastercard's cybersecurity and fraud prevention hub, then tailor journeys by audience, risk need and funnel stage. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention.html",
      short:
        "A clear starting point for Mastercard's cybersecurity story: protecting digital commerce with data, AI and network expertise. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention.html",
    },
    related_asset_ids: ["mc-cyber-solution", "mc-threat-intelligence", "mc-scam-protect"],
    ai_confidence_score: 0.93,
    metadata_status: "Human approved",
    content_usefulness: "Campaign hero asset",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-cyber-solution",
    title: "Cybersecurity",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Solution page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The cybersecurity solution page explains how Mastercard helps businesses assess cyber risk exposure, protect digital interactions and strengthen ecosystem trust. It highlights risk assessment, threat intelligence, DDoS and bot protection, Cyber Quant, RiskRecon and related solutions.",
    summary:
      "A deeper cybersecurity solution page with proof points and solution pathways for risk exposure, attack protection and ecosystem trust.",
    primary_topic: "Cybersecurity",
    secondary_topics: ["Cyber resilience", "Risk", "Threat intelligence", "Fraud prevention"],
    audience: ["Enterprises", "Banks", "Merchants", "Public sector"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Consideration",
    key_claims: [
      "Mastercard Cybersecurity evaluates risks, protects against attacks and strengthens ecosystem security.",
      "The page cites 32 million cybersecurity and identity risk events assessed every day.",
      "The page cites a 147% ROI for organizations using RiskRecon over three years from a Forrester study.",
    ],
    proof_points: [
      "32 million daily cybersecurity and identity risk events assessed.",
      "50+ memberships in regulatory, law enforcement, nonprofit, advocacy, academic and industry associations.",
      "147% ROI over three years for RiskRecon users, attributed to Forrester.",
    ],
    suggested_use:
      "Use after the overview page when campaign audiences need more detail on cybersecurity capabilities and proof.",
    suggested_sales_enablement_use:
      "Map the page sections to buyer pain points: assess risk, protect against attacks and organize trust.",
    linkedin_copy_recommendations: {
      executive:
        "Cybersecurity is becoming an ecosystem issue. Mastercard's cybersecurity page frames the challenge around risk exposure, attack protection and trust across the wider network. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity.html",
      sales:
        "For clients asking where to start on cyber risk, this page gives a useful path: assess exposure, protect against attacks and strengthen ecosystem trust. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity.html",
      launch:
        "Campaign idea: from risk visibility to ecosystem trust. This Mastercard cybersecurity page gives the solution architecture and proof points to support it. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity.html",
      short:
        "A practical Mastercard page for positioning cybersecurity as risk visibility, protection and ecosystem trust. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity.html",
    },
    related_asset_ids: ["mc-cyber-overview", "mc-threat-intelligence", "mc-cyber-fraud-risk"],
    ai_confidence_score: 0.91,
    metadata_status: "AI suggested",
    content_usefulness: "Supporting proof point",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-cyber-fraud-risk",
    title: "Cyber-fraud integration for the new age of risk",
    url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2026/cyber-fraud-integration-for-the-new-age-of-risk.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2026/cyber-fraud-integration-for-the-new-age-of-risk.html",
    source_type: "Mastercard insights",
    platform: "mastercard.com",
    format: "Report",
    language: "English",
    region: "Global",
    published_date: "2026-01-01",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The report page says payment fraud is rising while cyber and fraud teams are unifying. Mastercard commissioned Datos Insights to survey 100 financial institutions worldwide about integration hurdles and opportunities.",
    summary:
      "A research-led report on the need to integrate cyber and fraud teams, with global financial institution survey findings.",
    primary_topic: "Fraud prevention",
    secondary_topics: ["Cybersecurity", "Threat intelligence", "Risk management"],
    audience: ["Banks", "Issuers", "Enterprises", "Sales teams"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Proof",
    key_claims: [
      "Cyber and fraud teams are unifying to catch threats quicker.",
      "81% of surveyed financial institutions investing in cyber-fraud integration are rapidly advancing risk defenses.",
      "More than 60% of executives cite cross-domain talent and real-time data sharing as barriers.",
    ],
    proof_points: [
      "Survey of 100 financial institutions worldwide commissioned by Mastercard from Datos Insights.",
      "81% of FIs investing in cyber-fraud integration are rapidly advancing risk defenses.",
      "More than 60% of executives reported talent and real-time data-sharing barriers.",
    ],
    suggested_use:
      "Use as the strongest research proof point for a campaign about connecting fraud operations and cybersecurity teams.",
    suggested_sales_enablement_use:
      "A strong leave-behind for financial institution conversations about operational maturity and integration blockers.",
    linkedin_copy_recommendations: {
      executive:
        "Fraud and cybersecurity cannot be treated as separate fights. Mastercard-commissioned research with Datos Insights points to a clear shift toward cyber-fraud integration, while showing the operational barriers still to solve. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2026/cyber-fraud-integration-for-the-new-age-of-risk.html",
      sales:
        "A useful stat for FI conversations: 81% of surveyed institutions investing in cyber-fraud integration are rapidly advancing their defenses. The next challenge is talent and real-time data sharing. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2026/cyber-fraud-integration-for-the-new-age-of-risk.html",
      launch:
        "Campaign proof point: cyber-fraud integration is moving from idea to operating model. This Mastercard report gives the data, the barriers and the client conversation starter. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2026/cyber-fraud-integration-for-the-new-age-of-risk.html",
      short:
        "Cyber-fraud integration is becoming a new risk discipline. Mastercard's report shows why and where FIs are getting stuck. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2026/cyber-fraud-integration-for-the-new-age-of-risk.html",
    },
    related_asset_ids: ["mc-threat-intelligence", "mc-banks-threat-intelligence", "mc-cyber-solution"],
    ai_confidence_score: 0.96,
    metadata_status: "Human approved",
    content_usefulness: "Report/statistic source",
    url_status: "Accessible",
    duplicate_group: "cyber-fraud-integration",
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-agentic-security",
    title: "Security in the age of agentic",
    url: "https://www.mastercard.com/us/en/news-and-trends/stories/2026/cybersecurity-age-of-agentic.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/stories/2026/cybersecurity-age-of-agentic.html",
    source_type: "Mastercard newsroom",
    platform: "mastercard.com",
    format: "Perspective article",
    language: "English",
    region: "Global",
    published_date: "2026-05-21",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "Ann Johnson argues that AI-driven threats require faster, more predictive and more collaborative cybersecurity. The article emphasizes smaller ecosystem players, systemic risk and machine-speed attacks.",
    summary:
      "An executive thought-leadership article that frames AI-era cybersecurity around speed, prediction, collaboration and ecosystem protection.",
    primary_topic: "AI security",
    secondary_topics: ["Cybersecurity", "Cyber resilience", "Trust", "Small business security"],
    audience: ["Enterprises", "Public sector", "Policymakers", "Marketing teams"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Thought leadership",
    key_claims: [
      "AI-driven attacks increase the need for faster and more predictive defenses.",
      "Security resilience depends on protecting smaller players in the digital ecosystem.",
      "Cybersecurity is shifting from isolated incidents to systemic pressures.",
    ],
    proof_points: [
      "Executive byline from Ann Johnson, Executive Vice President, Security Solutions, Mastercard.",
      "Published May 21, 2026 on Mastercard Newsroom.",
    ],
    suggested_use:
      "Use as the executive POV for AI and cybersecurity campaigns, especially at the top of funnel.",
    suggested_sales_enablement_use:
      "Use selectively as a conversation opener for leaders already concerned about AI-enabled threats.",
    linkedin_copy_recommendations: {
      executive:
        "AI is changing the tempo of cyber risk. Ann Johnson's perspective for Mastercard argues that defenses now need to be faster, more predictive and more collaborative across the ecosystem. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2026/cybersecurity-age-of-agentic.html",
      sales:
        "For clients asking what agentic AI changes in cybersecurity, this piece is a good opener: risk moves faster, ecosystems are more connected and smaller players still matter. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2026/cybersecurity-age-of-agentic.html",
      launch:
        "Campaign angle: security at machine speed. Lead with Mastercard's executive POV on agentic AI, then support it with proof points from threat intelligence and cyber-fraud integration assets. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2026/cybersecurity-age-of-agentic.html",
      short:
        "Agentic AI raises the stakes for cyber resilience. Mastercard's POV: faster, more predictive, more collaborative security. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2026/cybersecurity-age-of-agentic.html",
    },
    related_asset_ids: ["mc-securing-tomorrow", "mc-small-business-security", "mc-threat-intelligence"],
    ai_confidence_score: 0.94,
    metadata_status: "AI suggested",
    content_usefulness: "Executive POV",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-securing-tomorrow",
    title: "Securing tomorrow: Preparing for an always-on, AI-powered future",
    url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-tomorrow-cybersecurity-2030-white-paper.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-tomorrow-cybersecurity-2030-white-paper.html",
    source_type: "Mastercard insights",
    platform: "mastercard.com",
    format: "White paper",
    language: "English",
    region: "Global",
    published_date: "2025-09-09",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The white paper preview describes a 2030 world of connected devices, autonomous agents and accounts, and argues that security and privacy must be fundamental to new platforms as cybercriminals use AI and synthetic identities.",
    summary:
      "Forward-looking white paper on AI-powered cyber threats, synthetic identity risk and how organizations need to evolve security for 2030.",
    primary_topic: "AI security",
    secondary_topics: ["Cybersecurity", "Identity", "Cyber resilience", "Data protection"],
    audience: ["Enterprises", "Banks", "Policymakers", "Marketing teams"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Thought leadership",
    key_claims: [
      "AI and autonomous agents will expand both commerce opportunity and cyber risk.",
      "Security and privacy must be built into new platforms.",
      "Organizations need more nimble and continually evolving cybersecurity postures.",
    ],
    proof_points: [
      "Published September 9, 2025 as a Mastercard white paper.",
      "Connects AI, synthetic identities and always-on digital commerce to future cyber risk.",
    ],
    suggested_use:
      "Use as a future-facing thought leadership anchor for AI security and resilience themes.",
    suggested_sales_enablement_use:
      "Useful for executive briefings where clients are planning 2027-2030 security roadmaps.",
    linkedin_copy_recommendations: {
      executive:
        "By 2030, connected devices and autonomous agents could reshape commerce. Mastercard's white paper argues that security and privacy need to be designed into that future from the start. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-tomorrow-cybersecurity-2030-white-paper.html",
      sales:
        "For clients planning beyond today's fraud controls, this Mastercard white paper connects AI, synthetic identity and always-on commerce to the next wave of cyber resilience. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-tomorrow-cybersecurity-2030-white-paper.html",
      launch:
        "Campaign theme: secure the AI-powered economy before it arrives. Use this white paper as the future-state anchor. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-tomorrow-cybersecurity-2030-white-paper.html",
      short:
        "A future-facing Mastercard white paper on AI, synthetic identity and always-on cybersecurity. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-tomorrow-cybersecurity-2030-white-paper.html",
    },
    related_asset_ids: ["mc-agentic-security", "mc-passkeys", "mc-identity"],
    ai_confidence_score: 0.92,
    metadata_status: "AI suggested",
    content_usefulness: "Campaign hero asset",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-small-business-security",
    title: "Securing small businesses: Understanding risk, building confidence and fighting back against cyber threats",
    url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-small-businesses-white-papers.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-small-businesses-white-papers.html",
    source_type: "Mastercard insights",
    platform: "mastercard.com",
    format: "White paper series",
    language: "English",
    region: "Global",
    published_date: "2025-11-03",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The series is based on Mastercard global small business cybersecurity research with more than 5,000 SME leaders. It says nearly half of SMEs have experienced a cyberattack and covers risk, confidence, expert support and next-step solutions.",
    summary:
      "A strong SME-focused research series that turns cybersecurity risk into a practical confidence and resilience story.",
    primary_topic: "Small business security",
    secondary_topics: ["Cybersecurity", "Cyber resilience", "Fraud prevention", "Trust"],
    audience: ["Small businesses", "Merchants", "Marketing teams", "Sales teams"],
    business_area: "Small business",
    funnel_stage: "Education",
    key_claims: [
      "Nearly half of SMEs in Mastercard research have experienced a cyberattack.",
      "Cybersecurity is presented as essential for resilience and business confidence.",
      "The series covers threat awareness, business impact, expert support and solution needs.",
    ],
    proof_points: [
      "Research based on insights from more than 5,000 SME leaders across industries and regions.",
      "Four-part white paper series focused on the SME cybersecurity journey.",
    ],
    suggested_use:
      "Use as a topic cluster hero for small business cybersecurity, with modular assets for nurture and sales enablement.",
    suggested_sales_enablement_use:
      "Equip small business and merchant-facing teams with stats and pain points for cyber-resilience conversations.",
    linkedin_copy_recommendations: {
      executive:
        "Small businesses are central to the digital economy, but they are increasingly exposed to cyber risk. Mastercard's global SME research turns that risk into a practical resilience conversation. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-small-businesses-white-papers.html",
      sales:
        "A useful client conversation starter: Mastercard research with more than 5,000 SME leaders found that nearly half have experienced a cyberattack. The next question is how to build confidence and access practical support. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-small-businesses-white-papers.html",
      launch:
        "Campaign angle: help small businesses fight back against cyber threats. This Mastercard white paper series gives the research, audience pain points and solution journey. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-small-businesses-white-papers.html",
      short:
        "Mastercard's SME cybersecurity series gives marketers a clear resilience story backed by global small business research. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/securing-small-businesses-white-papers.html",
    },
    related_asset_ids: ["mc-agentic-security", "mc-cyber-solution", "mc-scam-protect"],
    ai_confidence_score: 0.97,
    metadata_status: "Human approved",
    content_usefulness: "Report/statistic source",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-pqc-whitepaper",
    title: "Migration to post-quantum cryptography",
    url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/post-quantum-cryptography-white-paper.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/post-quantum-cryptography-white-paper.html",
    source_type: "Mastercard insights",
    platform: "mastercard.com",
    format: "White paper",
    language: "English",
    region: "Global",
    published_date: "2025-10-20",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The white paper page explains the risk that quantum computers could undermine current public-key cryptography and urges financial organizations to plan for post-quantum cryptography and quantum-safe migration.",
    summary:
      "Technical thought leadership on preparing financial institutions for quantum-safe cryptography migration.",
    primary_topic: "Post-quantum security",
    secondary_topics: ["Data protection", "Cyber resilience", "Risk", "Cybersecurity"],
    audience: ["Banks", "Enterprises", "Developers", "Policymakers"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Education",
    key_claims: [
      "Quantum computing threatens the cryptographic foundations of financial systems.",
      "Financial organizations should proactively plan for quantum-safe practices.",
      "Early adopters will be better positioned to protect assets and maintain resilience.",
    ],
    proof_points: [
      "Published October 20, 2025 as a Mastercard white paper.",
      "Connects post-quantum cryptography, quantum key distribution and migration planning.",
    ],
    suggested_use:
      "Use for technical education and policy-facing content around future data protection risks.",
    suggested_sales_enablement_use:
      "Use with financial institution security and architecture teams exploring cryptographic inventory and migration.",
    linkedin_copy_recommendations: {
      executive:
        "Quantum-safe planning is becoming part of resilience planning. Mastercard's white paper explains why financial organizations should start preparing for post-quantum cryptography now. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/post-quantum-cryptography-white-paper.html",
      sales:
        "For banks and financial institutions asking about quantum risk, this Mastercard white paper offers a practical starting point for cryptographic migration planning. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/post-quantum-cryptography-white-paper.html",
      launch:
        "Campaign angle: prepare for the quantum-safe future. Use Mastercard's PQC white paper as the technical anchor. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/post-quantum-cryptography-white-paper.html",
      short:
        "Mastercard's PQC white paper helps financial organizations plan for quantum-safe security. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/post-quantum-cryptography-white-paper.html",
    },
    related_asset_ids: ["mc-post-quantum-explainer", "mc-securing-tomorrow"],
    ai_confidence_score: 0.94,
    metadata_status: "AI suggested",
    content_usefulness: "Background reading",
    url_status: "Accessible",
    duplicate_group: "post-quantum",
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-post-quantum-explainer",
    title: "What is post-quantum cryptography?",
    url: "https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-post-quantum-cryptography.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-post-quantum-cryptography.html",
    source_type: "Mastercard newsroom",
    platform: "mastercard.com",
    format: "Explainer article",
    language: "English",
    region: "Global",
    published_date: "2025-01-01",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The explainer says quantum computing is not a current threat, but attackers may harvest encrypted data now to decrypt later. It explains who should worry, what PQC means and how banks can prepare.",
    summary:
      "Accessible explainer for marketers and nontechnical stakeholders on quantum threats, harvest-now-decrypt-later risk and PQC migration.",
    primary_topic: "Post-quantum security",
    secondary_topics: ["Data protection", "Risk", "Cybersecurity"],
    audience: ["Banks", "Enterprises", "Marketing teams", "Policymakers"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Education",
    key_claims: [
      "Quantum computing is not a present-day threat, but long-lived sensitive data is exposed to harvest-now-decrypt-later risk.",
      "Banks, healthcare systems and governments should begin planning because they store sensitive data for long periods.",
      "PQC is designed to resist attacks from quantum computers and can often strengthen existing cryptographic systems.",
    ],
    proof_points: [
      "The article names banks, healthcare systems and governments as priority planners.",
      "It references EU transition timing for critical infrastructure by 2030.",
    ],
    suggested_use:
      "Use as the plain-English companion to the PQC white paper for campaign nurture and stakeholder alignment.",
    suggested_sales_enablement_use:
      "Send before a technical white paper to help business stakeholders understand the issue.",
    linkedin_copy_recommendations: {
      executive:
        "Quantum risk can sound distant, but long-lived data changes the timeline. Mastercard's explainer makes the case for planning now, especially for organizations that store sensitive data over time. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-post-quantum-cryptography.html",
      sales:
        "Need a plain-English way to introduce post-quantum cryptography? This Mastercard explainer covers the threat, who should care and how banks can prepare. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-post-quantum-cryptography.html",
      launch:
        "Campaign pairing: lead with the PQC explainer, then offer the migration white paper for deeper planning. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-post-quantum-cryptography.html",
      short:
        "A helpful Mastercard explainer on quantum risk, sensitive data and post-quantum cryptography. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-post-quantum-cryptography.html",
    },
    related_asset_ids: ["mc-pqc-whitepaper", "mc-securing-tomorrow"],
    ai_confidence_score: 0.9,
    metadata_status: "AI suggested",
    content_usefulness: "Background reading",
    url_status: "Accessible",
    duplicate_group: "post-quantum",
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-tokenization",
    title: "What is tokenization? A primer on card tokenization",
    url: "https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-tokenization.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-tokenization.html",
    source_type: "Mastercard newsroom",
    platform: "mastercard.com",
    format: "Explainer article",
    language: "English",
    region: "Global",
    published_date: "2024-03-19",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The explainer describes tokenization across mobile wallets, card-on-file payments, guest checkout and agentic commerce. It says tokens reduce exposure of card details and can pair with cryptograms and authentication.",
    summary:
      "A practical explainer on how tokenization protects payment data across contactless, e-commerce, card-on-file and agentic commerce scenarios.",
    primary_topic: "Tokenization",
    secondary_topics: ["Data protection", "Authentication", "Fraud prevention", "Trust"],
    audience: ["Consumers", "Merchants", "Banks", "Developers"],
    business_area: "Tokenization",
    funnel_stage: "Education",
    key_claims: [
      "Tokenization replaces card details with tokens that help secure payments.",
      "Tokens support digital wallets, card-on-file commerce, guest checkout and agentic transactions.",
      "Mastercard positions tokenization as invisible technology behind safer payments.",
    ],
    proof_points: [
      "The article was originally published March 19, 2024 and updated with new information.",
      "The overview page cites 4 billion tokenized transactions secured each month with Mastercard 2026 data.",
    ],
    suggested_use:
      "Use as a foundational education asset whenever campaigns reference tokenization, passkeys or secure digital commerce.",
    suggested_sales_enablement_use:
      "Useful for merchant and issuer teams explaining tokenization in simple, customer-friendly language.",
    linkedin_copy_recommendations: {
      executive:
        "The best security often works quietly. Mastercard's tokenization explainer shows how card details can be protected across wallets, e-commerce and emerging agentic commerce. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-tokenization.html",
      sales:
        "Need a simple way to explain tokenization to clients? Mastercard's primer covers wallets, card-on-file, guest checkout and agentic commerce in plain language. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-tokenization.html",
      launch:
        "Campaign angle: the invisible security behind digital payments. Pair Mastercard's tokenization primer with passkey and authentication content. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-tokenization.html",
      short:
        "Mastercard's tokenization primer explains the invisible tech behind safer digital payments. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2025/what-is-tokenization.html",
    },
    related_asset_ids: ["mc-passkeys", "mc-cyber-overview"],
    ai_confidence_score: 0.91,
    metadata_status: "Human edited",
    content_usefulness: "Background reading",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-passkeys",
    title: "What is a passkey? Here's everything you need to know",
    url: "https://www.mastercard.com/us/en/news-and-trends/stories/2024/what-is-a-passkey.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/stories/2024/what-is-a-passkey.html",
    source_type: "Mastercard newsroom",
    platform: "mastercard.com",
    format: "Explainer article",
    language: "English",
    region: "Global",
    published_date: "2024-08-29",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The article explains passkeys, why they are safer than passwords and how payment passkeys can authenticate cardholders during e-commerce transactions using device biometrics.",
    summary:
      "A consumer-friendly authentication explainer that links passkeys, biometric checkout, Click to Pay and tokenization.",
    primary_topic: "Authentication",
    secondary_topics: ["Identity", "Tokenization", "Trust", "Data protection"],
    audience: ["Consumers", "Merchants", "Banks", "Developers"],
    business_area: "Digital identity",
    funnel_stage: "Education",
    key_claims: [
      "Passkeys are linked to a website and account and unlocked by the legitimate user.",
      "Payment passkeys can authenticate cardholders during online payment flows.",
      "Passkeys paired with Click to Pay and tokenization can simplify checkout.",
    ],
    proof_points: [
      "First published August 29, 2024 and updated April 30, 2026.",
      "The article references Mastercard Payment Passkey Service for merchants.",
    ],
    suggested_use:
      "Use as an accessible explainer in authentication, digital identity and secure checkout campaigns.",
    suggested_sales_enablement_use:
      "Useful for teams explaining why biometric payment authentication can improve both security and experience.",
    linkedin_copy_recommendations: {
      executive:
        "Passwords are giving way to more secure, simpler authentication. Mastercard's passkey explainer connects biometric sign-in, payment authentication and tokenization. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2024/what-is-a-passkey.html",
      sales:
        "For merchant conversations about checkout security, this passkey explainer is a clear primer on authentication, Click to Pay and tokenization. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2024/what-is-a-passkey.html",
      launch:
        "Campaign pairing: passkeys plus tokenization equals a simpler secure checkout story. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2024/what-is-a-passkey.html",
      short:
        "A clear Mastercard explainer on passkeys, biometric authentication and secure checkout. Source: https://www.mastercard.com/us/en/news-and-trends/stories/2024/what-is-a-passkey.html",
    },
    related_asset_ids: ["mc-tokenization", "mc-identity"],
    ai_confidence_score: 0.89,
    metadata_status: "AI suggested",
    content_usefulness: "Social-selling asset",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-threat-intelligence",
    title: "Mastercard Threat Intelligence",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/mastercard-threat-intelligence.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/mastercard-threat-intelligence.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Product page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The product page positions Mastercard Threat Intelligence as a way to connect cyber signals with fraud workflows to defend against emerging payment threats, act earlier and reduce losses.",
    summary:
      "Product page for Mastercard Threat Intelligence, strong for cyber-fraud integration and proactive fraud defense narratives.",
    primary_topic: "Threat intelligence",
    secondary_topics: ["Fraud prevention", "Cybersecurity", "Risk"],
    audience: ["Banks", "Issuers", "Enterprises", "Sales teams"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Consideration",
    key_claims: [
      "Mastercard Threat Intelligence connects cyber signals with fraud workflows.",
      "The solution is positioned to help organizations act earlier against emerging payment threats.",
    ],
    proof_points: [
      "Included in Mastercard cybersecurity solution pathways.",
      "Connected to the broader cyber-fraud integration report and threat intelligence content cluster.",
    ],
    suggested_use:
      "Use as a lower-funnel destination for campaign audiences engaging with cyber-fraud integration themes.",
    suggested_sales_enablement_use:
      "Primary sales follow-up asset for banks asking how to operationalize threat intelligence against payment fraud.",
    linkedin_copy_recommendations: {
      executive:
        "When cyber signals and fraud workflows are connected, organizations can move from reaction to earlier action. Mastercard Threat Intelligence is built around that integration opportunity. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/mastercard-threat-intelligence.html",
      sales:
        "For FI teams focused on payment fraud, Mastercard Threat Intelligence offers a practical bridge between cyber indicators and fraud operations. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/mastercard-threat-intelligence.html",
      launch:
        "Campaign next step: after the cyber-fraud integration report, route engaged audiences to Mastercard Threat Intelligence. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/mastercard-threat-intelligence.html",
      short:
        "Mastercard Threat Intelligence connects cyber signals with fraud workflows to support earlier action. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/mastercard-threat-intelligence.html",
    },
    related_asset_ids: ["mc-cyber-fraud-risk", "mc-banks-threat-intelligence", "mc-cyber-solution"],
    ai_confidence_score: 0.86,
    metadata_status: "AI suggested",
    content_usefulness: "Sales follow-up",
    url_status: "Accessible",
    duplicate_group: "threat-intelligence",
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-banks-threat-intelligence",
    title: "How banks prevent cyber fraud with improved threat intelligence",
    url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/how-banks-prevent-cyber-fraud-with-improved-threat-intelligence.html",
    canonical_url: "https://www.mastercard.com/us/en/news-and-trends/Insights/2025/how-banks-prevent-cyber-fraud-with-improved-threat-intelligence.html",
    source_type: "Mastercard insights",
    platform: "mastercard.com",
    format: "Blog article",
    language: "English",
    region: "Global",
    published_date: "2025-01-01",
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The article sits in Mastercard's cybersecurity content cluster and focuses on how banks can prevent cyber fraud by using improved threat intelligence and spotting indicators earlier.",
    summary:
      "A bank-focused activation article that bridges thought leadership and product interest around threat intelligence.",
    primary_topic: "Threat intelligence",
    secondary_topics: ["Fraud prevention", "Cybersecurity", "Risk management"],
    audience: ["Banks", "Issuers", "Sales teams"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Sales enablement",
    key_claims: [
      "Banks can reduce cyber fraud by spotting early indicators from cybersecurity incidents.",
      "Threat intelligence can help teams act faster before losses grow.",
    ],
    proof_points: [
      "Featured in Mastercard cybersecurity solution page as related content.",
      "Directly tied to Mastercard Threat Intelligence content journey.",
    ],
    suggested_use:
      "Use as a mid- to lower-funnel nurture asset for bank audiences after they engage with the report.",
    suggested_sales_enablement_use:
      "Good email follow-up asset after FI meetings focused on cyber-fraud fusion.",
    linkedin_copy_recommendations: {
      executive:
        "Banks need earlier warning signals to fight cyber fraud. Mastercard's article connects improved threat intelligence with faster fraud prevention action. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/how-banks-prevent-cyber-fraud-with-improved-threat-intelligence.html",
      sales:
        "For bank conversations on cyber fraud, this Mastercard article is a focused follow-up on using threat intelligence to spot early indicators and reduce losses. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/how-banks-prevent-cyber-fraud-with-improved-threat-intelligence.html",
      launch:
        "Campaign nurture idea: report downloaders interested in cyber-fraud integration should receive this bank-focused threat intelligence follow-up. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/how-banks-prevent-cyber-fraud-with-improved-threat-intelligence.html",
      short:
        "A bank-focused Mastercard article on preventing cyber fraud with improved threat intelligence. Source: https://www.mastercard.com/us/en/news-and-trends/Insights/2025/how-banks-prevent-cyber-fraud-with-improved-threat-intelligence.html",
    },
    related_asset_ids: ["mc-threat-intelligence", "mc-cyber-fraud-risk"],
    ai_confidence_score: 0.78,
    metadata_status: "AI suggested",
    content_usefulness: "Sales follow-up",
    url_status: "Accessible",
    duplicate_group: "threat-intelligence",
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-scam-protect",
    title: "Scam Protect",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/scam-protect.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/scam-protect.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Product page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The product page positions Scam Protect as advanced AI-powered fraud prevention for helping identify and prevent scams, connected to Mastercard's cybersecurity and fraud prevention portfolio.",
    summary:
      "Product page for scam prevention, useful for consumer protection, bank trust and fraud prevention campaign angles.",
    primary_topic: "Scams",
    secondary_topics: ["Fraud prevention", "Consumer protection", "AI security", "Trust"],
    audience: ["Consumers", "Banks", "Issuers", "Merchants"],
    business_area: "Consumer protection",
    funnel_stage: "Consideration",
    key_claims: [
      "Mastercard positions Scam Protect as AI-powered scam and fraud prevention.",
      "The page is part of the cybersecurity portfolio and supports consumer trust narratives.",
    ],
    proof_points: ["Official Mastercard product page.", "Connected to Mastercard's cybersecurity and fraud prevention navigation."],
    suggested_use:
      "Use in campaigns focused on consumer protection, scam prevention and trust in digital payments.",
    suggested_sales_enablement_use:
      "Use as a follow-up for issuers and banks prioritizing scam detection and consumer protection.",
    linkedin_copy_recommendations: {
      executive:
        "Scams are a trust problem as much as a fraud problem. Mastercard's Scam Protect page shows how AI-powered prevention fits into the broader cybersecurity portfolio. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/scam-protect.html",
      sales:
        "For issuer conversations about scam prevention, Mastercard Scam Protect is a focused product destination tied to AI-powered fraud prevention. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/scam-protect.html",
      launch:
        "Campaign angle: protect people from scams before trust is lost. Route engaged bank and issuer audiences to Mastercard Scam Protect. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/scam-protect.html",
      short:
        "Mastercard Scam Protect supports the consumer protection side of the cybersecurity story. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/cybersecurity/scam-protect.html",
    },
    related_asset_ids: ["mc-cyber-overview", "mc-small-business-security", "mc-risk-decisioning"],
    ai_confidence_score: 0.84,
    metadata_status: "AI suggested",
    content_usefulness: "Sales follow-up",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-identity",
    title: "Identity",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/identity.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/identity.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Solution page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "Mastercard identity content is positioned around providing trust in every digital interaction and verifying customers with confidence.",
    summary:
      "Solution page for identity verification and trust in digital interactions, relevant to authentication and fraud prevention journeys.",
    primary_topic: "Identity",
    secondary_topics: ["Authentication", "Trust", "Fraud prevention", "Data protection"],
    audience: ["Merchants", "Banks", "Fintechs", "Developers"],
    business_area: "Digital identity",
    funnel_stage: "Consideration",
    key_claims: [
      "Digital identity solutions help provide trust in digital interactions.",
      "Identity is positioned as part of Mastercard's cybersecurity and fraud prevention portfolio.",
    ],
    proof_points: ["Official Mastercard identity solution page.", "Linked from the cybersecurity and fraud prevention hub."],
    suggested_use:
      "Use in campaigns about trusted digital interactions, authentication and customer verification.",
    suggested_sales_enablement_use:
      "Route merchant and fintech discussions from identity pain points to solution detail.",
    linkedin_copy_recommendations: {
      executive:
        "Trusted digital interactions depend on strong identity. Mastercard's Identity page connects verification, trust and fraud prevention within the wider security portfolio. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/identity.html",
      sales:
        "For clients focused on verification and trust, Mastercard's Identity page is a useful next step after passkey or fraud-prevention content. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/identity.html",
      launch:
        "Campaign angle: verify customers with confidence. Pair Identity with passkeys and tokenization content for a complete trusted checkout story. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/identity.html",
      short:
        "Mastercard Identity supports a trust-first story for digital interactions. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/identity.html",
    },
    related_asset_ids: ["mc-passkeys", "mc-tokenization", "mc-securing-tomorrow"],
    ai_confidence_score: 0.81,
    metadata_status: "AI suggested",
    content_usefulness: "Supporting proof point",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-risk-decisioning",
    title: "Risk decisioning and fraud mitigation solutions",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/risk-decisioning.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/risk-decisioning.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Solution page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The risk decisioning page sits in the cybersecurity and fraud prevention portfolio and focuses on using AI and machine learning decisioning tools to navigate evolving risk.",
    summary:
      "Solution page for AI and machine learning powered risk decisioning, relevant to fraud prevention and payment risk workflows.",
    primary_topic: "Risk",
    secondary_topics: ["Fraud prevention", "AI security", "Cybersecurity"],
    audience: ["Banks", "Issuers", "Merchants", "Acquirers"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Consideration",
    key_claims: [
      "Risk decisioning helps organizations navigate evolving digital risk.",
      "The solution area connects AI and machine learning with payment fraud mitigation.",
    ],
    proof_points: ["Official Mastercard risk decisioning page.", "Part of the Mastercard cybersecurity and fraud prevention portfolio."],
    suggested_use:
      "Use as a lower-funnel destination for audiences interested in fraud decisioning and AI-led risk management.",
    suggested_sales_enablement_use:
      "Useful follow-up for issuers and acquirers discussing transaction risk and fraud mitigation.",
    linkedin_copy_recommendations: {
      executive:
        "Risk decisions now need to happen at digital speed. Mastercard's risk decisioning page connects AI, machine learning and fraud mitigation within the security portfolio. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/risk-decisioning.html",
      sales:
        "For issuer and acquirer conversations about fraud decisioning, this Mastercard page is a focused destination for risk and AI-enabled mitigation. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/risk-decisioning.html",
      launch:
        "Campaign next step: route risk-focused audiences from thought leadership into Mastercard risk decisioning. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/risk-decisioning.html",
      short:
        "Mastercard risk decisioning links AI-powered decisions with fraud mitigation. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/risk-decisioning.html",
    },
    related_asset_ids: ["mc-cyber-overview", "mc-scam-protect", "mc-cyber-fraud-risk"],
    ai_confidence_score: 0.82,
    metadata_status: "AI suggested",
    content_usefulness: "Supporting proof point",
    url_status: "Accessible",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
  {
    id: "mc-financial-crime",
    title: "Financial crime management",
    url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/financial-crime-management.html",
    canonical_url: "https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/financial-crime-management.html",
    source_type: "Mastercard website page",
    platform: "mastercard.com",
    format: "Solution page",
    language: "English",
    region: "US",
    published_date: null,
    last_seen_date: "2026-06-18",
    last_crawled_date: "2026-06-18",
    raw_text:
      "The financial crime management page is part of Mastercard's cybersecurity and fraud prevention portfolio and focuses on safeguarding the ecosystem from bad actors with scam protection and anti-money laundering services.",
    summary:
      "Solution page for financial crime management, scam protection and anti-money-laundering themes.",
    primary_topic: "Fraud prevention",
    secondary_topics: ["Scams", "Risk", "Trust"],
    audience: ["Banks", "Issuers", "Public sector", "Enterprises"],
    business_area: "Cyber and intelligence",
    funnel_stage: "Consideration",
    key_claims: [
      "Financial crime management helps safeguard the ecosystem from bad actors.",
      "The solution area connects scam protection, AML and fraud prevention.",
    ],
    proof_points: ["Official Mastercard financial crime management page.", "Linked from the cybersecurity and fraud prevention hub."],
    suggested_use:
      "Use for campaign journeys focused on bad actors, financial crime and ecosystem trust.",
    suggested_sales_enablement_use:
      "Useful for bank and issuer conversations where scam prevention overlaps with compliance and financial crime.",
    linkedin_copy_recommendations: {
      executive:
        "Financial crime, scams and fraud prevention are increasingly connected. Mastercard's financial crime management page frames the ecosystem protection challenge. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/financial-crime-management.html",
      sales:
        "For clients dealing with scams, AML and fraud prevention in parallel, this Mastercard solution page gives a clear route into financial crime management. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/financial-crime-management.html",
      launch:
        "Campaign angle: safeguard the ecosystem from bad actors. Pair financial crime management with Scam Protect and risk decisioning. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/financial-crime-management.html",
      short:
        "Mastercard financial crime management connects scam protection, AML and fraud prevention. Source: https://www.mastercard.com/us/en/business/cybersecurity-fraud-prevention/financial-crime-management.html",
    },
    related_asset_ids: ["mc-scam-protect", "mc-risk-decisioning", "mc-cyber-overview"],
    ai_confidence_score: 0.79,
    metadata_status: "AI suggested",
    content_usefulness: "Sales follow-up",
    url_status: "Needs review",
    duplicate_group: null,
    created_at: "2026-06-18T09:00:00Z",
    updated_at: "2026-06-18T09:00:00Z",
    page_views: null,
    search_clicks: null,
    search_impressions: null,
    social_engagements: null,
    video_views: null,
    source_performance_platform: null,
  },
];

export const topicClusters = [
  {
    id: "fraud-prevention",
    name: "Fraud prevention",
    topics: ["Fraud prevention", "Threat intelligence", "Risk"],
    gap: "Strong product and proof coverage, but needs more vertical-specific activation for merchants and acquirers.",
    priority: "High",
  },
  {
    id: "identity-auth",
    name: "Identity and authentication",
    topics: ["Identity", "Authentication", "Tokenization"],
    gap: "Good explainers, limited campaign-ready proof points for enterprise identity buyers.",
    priority: "Medium",
  },
  {
    id: "cyber-resilience",
    name: "Cyber resilience",
    topics: ["Cyber resilience", "Cybersecurity", "Post-quantum security"],
    gap: "Strong thought leadership, but more sales activation material would help convert interest.",
    priority: "High",
  },
  {
    id: "data-security",
    name: "Data security",
    topics: ["Data protection", "Tokenization", "Post-quantum security"],
    gap: "Useful education assets, but the story is fragmented across tokenization, PQC and identity.",
    priority: "Medium",
  },
  {
    id: "scams-protection",
    name: "Scams and consumer protection",
    topics: ["Scams", "Consumer protection", "Fraud prevention"],
    gap: "Product coverage exists, but there are fewer public proof assets in the seed set.",
    priority: "Medium",
  },
  {
    id: "ai-security",
    name: "AI and security",
    topics: ["AI security", "Cybersecurity", "Threat intelligence"],
    gap: "Strong thought leadership, needs more case studies and concrete proof points for campaigns.",
    priority: "High",
  },
  {
    id: "small-business",
    name: "Small business cybersecurity",
    topics: ["Small business security", "Cyber resilience", "Scams"],
    gap: "Excellent research anchor, but needs shorter social and sales-ready derivatives.",
    priority: "High",
  },
  {
    id: "enterprise",
    name: "Enterprise cybersecurity",
    topics: ["Cybersecurity", "Risk", "Threat intelligence"],
    gap: "Good solution coverage, but duplicate themes across pages should be coordinated.",
    priority: "High",
  },
];

export const initialSources = [
  {
    id: "source-mastercard-us",
    type: "Mastercard domain",
    label: "Mastercard US website",
    url: "https://www.mastercard.com/us/en/",
    cadence: "Daily",
    owner: "Content ops",
    enabled: true,
    last_checked: "2026-06-18",
    notes: "Primary public website source for English-language business and newsroom content.",
  },
  {
    id: "source-newsroom",
    type: "Newsroom URL",
    label: "Mastercard global newsroom",
    url: "https://www.mastercard.com/news/",
    cadence: "Daily",
    owner: "PR and comms",
    enabled: true,
    last_checked: "2026-06-18",
    notes: "Global stories, explainers, perspectives and featured topic pages.",
  },
  {
    id: "source-cyber-topic",
    type: "Featured topic",
    label: "Cybersecurity featured topic",
    url: "https://www.mastercard.com/us/en/news-and-trends/featured-topic/cybersecurity-featured-topic.html",
    cadence: "Daily",
    owner: "Cyber marketing",
    enabled: true,
    last_checked: "2026-06-18",
    notes: "Topic hub for cybersecurity stories, articles and reports.",
  },
  {
    id: "source-reports",
    type: "Report/PDF URL",
    label: "Cybersecurity reports and white papers",
    url: "https://www.mastercard.com/us/en/news-and-trends/Insights/",
    cadence: "Weekly",
    owner: "Thought leadership",
    enabled: true,
    last_checked: "2026-06-18",
    notes: "Manual review for gated downloads and PDF links.",
  },
  {
    id: "source-linkedin",
    type: "Official social handle",
    label: "Mastercard LinkedIn",
    url: "https://www.linkedin.com/company/mastercard/",
    cadence: "Weekly",
    owner: "Social",
    enabled: false,
    last_checked: null,
    notes: "Use official API or manual URL input only.",
  },
  {
    id: "source-exec-placeholder",
    type: "Executive profile",
    label: "C-level decision-maker public posts",
    url: "",
    cadence: "Weekly",
    owner: "Comms",
    enabled: false,
    last_checked: null,
    notes: "Open question: confirm approved profiles before monitoring.",
  },
];
